const newCollection = [
  {
    id: 24,
    name: "Hayami",
    price: 1299,
    originalPrice: 1399,
    inStock: true,
    onSale: false,
    category: "newCollection",
    imageSrc: [
      "/images/newCollection/Hayami1.jpg",
      "/images/newCollection/Hayami2.jpg",
      "/images/newCollection/Hayami3.jpg",
      "/images/newCollection/Hayami4.jpg",
    ],
  },
  {
    id: 25,
    name: "Shinra",
    price: 1399,
    originalPrice: 1499,
    inStock: true,
    onSale: true,
    category: "newCollection",
    imageSrc: [
      "/images/newCollection/Shinra1.jpg",
      "/images/newCollection/Shinra2.jpg",
      "/images/newCollection/Shinra3.jpg",
      "/images/newCollection/Shinra4.jpg",
    ],
  },
  {
    id: 26,
    name: "Elwyn",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "newCollection",
    imageSrc: [
      "/images/newCollection/Elwyn1.jpg",
      "/images/newCollection/Elwyn2.jpg",
      "/images/newCollection/Elwyn3.jpg",
      "/images/newCollection/Elwyn4.jpg",
    ],
  },
  {
    id: 27,
    name: "Kureha",
    price: 899,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "newCollection",
    imageSrc: [
      "/images/newCollection/Kureha1.jpg",
      "/images/newCollection/Kureha2.jpg",
      "/images/newCollection/Kureha3.jpg",
      "/images/newCollection/Kureha4.jpg",
    ],
  },

  {
    id: 28,
    name: "Xecty",
    price: 999,
    originalPrice: 1399,
    inStock: true,
    onSale: false,
    category: "newCollection",
    imageSrc: [
      "/images/newCollection/Xecty2.jpg",
      "/images/newCollection/Xecty1.jpg",
      "/images/newCollection/Xecty3.jpg",
      "/images/newCollection/Xecty4.jpg",
    ],
  },
  {
    id: 29,
    name: "Hikamori",
    price: 599,
    originalPrice: 1399,
    inStock: true,
    onSale: false,
    category: "newCollection",
    imageSrc: [
      "/images/newCollection/Hikamori1.jpg",
      "/images/newCollection/Hikamori2.jpg",
      "/images/newCollection/Hikamori3.jpg",
      "/images/newCollection/Hikamori4.jpg",
    ],
  },
  {
    id: 38,
    name: "Ikki",
    price: 1999,
    originalPrice: 1999,
    inStock: true,
    onSale: false,
    category: "newCollection",
    imageSrc: [
      "/images/newCollection/Ikki1.jpg",
      "/images/newCollection/Ikki2.jpg",
      "/images/newCollection/Ikki3.jpg",
      "/images/newCollection/Ikki4.jpg",
    ],
  },
  {
    id: 39,
    name: "Celestia",
    price: 1999,
    originalPrice: 1999,
    inStock: true,
    onSale: false,
    category: "newCollection",
    imageSrc: [
      "/images/newCollection/Celestia1.jpg",
      "/images/newCollection/Celestia2.jpg",
      "/images/newCollection/Celestia3.jpg",
      "/images/newCollection/Celestia4.jpg",
    ],
  },
];

const sale = [
  {
    id: 1,
    name: "Senhime Tanaka",
    price: 999,
    originalPrice: 1299,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Senhime1.jpg",
      "/images/sale/Senhime2.jpg",
      "/images/sale/Senhime3.jpg",
      "/images/sale/Senhime4.jpg",
    ],
  },
  {
    id: 2,
    name: "Kamael Sato",
    price: 899,
    originalPrice: 1099,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Kamael1.jpg",
      "/images/sale/Kamael2.jpg",
      "/images/sale/Kamael3.jpg",
      "/images/sale/Kamael4.jpg",
    ],
  },
  {
    id: 5,
    name: "Reimu Hakurei",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Reimu1.jpg",
      "/images/sale/Reimu2.jpg",
      "/images/sale/Reimu3.jpg",
      "/images/sale/Reimu4.jpg",
    ],
  },
  {
    id: 6,
    name: "Yukimura Sanada",
    price: 899,
    originalPrice: 1099,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Yukimura1.jpg",
      "/images/sale/Yukimura2.jpg",
      "/images/sale/Yukimura3.jpg",
      "/images/sale/Yukimura4.jpg",
    ],
  },
  {
    id: 8,
    name: "Hatsune Miku",
    price: 1199,
    originalPrice: 1499,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Hatsune1.jpg",
      "/images/sale/Hatsune2.jpg",
      "/images/sale/Hatsune3.jpg",
      "/images/sale/Hatsune4.jpg",
    ],
  },
  {
    id: 11,
    name: "Miya Sakamoto",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Miya1.jpg",
      "/images/sale/Miya2.jpg",
      "/images/sale/Miya3.jpg",
      "/images/sale/Miya4.jpg",
    ],
  },
  {
    id: 12,
    name: "Jin Xue",
    price: 1099,
    originalPrice: 1999,
    inStock: false,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Jin1.jpg",
      "/images/sale/Jin2.jpg",
      "/images/sale/Jin3.jpg",
      "/images/sale/Jin4.jpg",
    ],
  },
  {
    id: 13,
    name: "Raquel Lolita",
    price: 1999,
    originalPrice: 2199,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Raquel1.jpg",
      "/images/sale/Raquel2.jpg",
      "/images/sale/Raquel3.jpg",
      "/images/sale/Raquel4.jpg",
    ],
  },
  {
    id: 14,
    name: "Louise Gothic",
    price: 999,
    originalPrice: 1099,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Louise1.jpg",
      "/images/sale/Louise2.jpg",
      "/images/sale/Louise3.jpg",
      "/images/sale/Louise4.jpg",
    ],
  },
  {
    id: 16,
    name: "Melissa Seraphy",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Melissa1.jpg",
      "/images/sale/Melissa2.jpg",
      "/images/sale/Melissa3.jpg",
      "/images/sale/Melissa4.jpg",
    ],
  },
  {
    id: 18,
    name: "Haruhi Taniguchi",
    price: 999,
    originalPrice: 1299,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/Haruhi1.jpg",
      "/images/sale/Haruhi2.jpg",
      "/images/sale/Haruhi3.jpg",
      "/images/sale/Haruhi4.jpg",
    ],
  },
  {
    id: 20,
    name: "LLenn Mori",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: [
      "/images/sale/LLenn1.jpg",
      "/images/sale/LLenn2.jpg",
      "/images/sale/LLenn3.jpg",
      "/images/sale/LLenn4.jpg",
    ],
  },
];

const bestSellings = [
  {
    id: 3,
    name: "Komi Nakamura",
    price: 999,
    originalPrice: 999,
    inStock: false,
    onSale: false,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Komi1.jpg",
      "/images/bestSellings/Komi2.jpg",
      "/images/bestSellings/Komi3.jpg",
      "/images/bestSellings/Komi4.jpg",
    ],
  },
  {
    id: 4,
    name: "Toka Yamada",
    price: 999,
    originalPrice: 999,
    inStock: true,
    onSale: false,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Toka1.jpg",
      "/images/bestSellings/Toka2.jpg",
      "/images/bestSellings/Toka3.jpg",
      "/images/bestSellings/Toka4.jpg",
    ],
  },
  {
    id: 7,
    name: "Ryan Suzuki",
    price: 1299,
    originalPrice: 1599,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Ryan1.jpg",
      "/images/bestSellings/Ryan2.jpg",
      "/images/bestSellings/Ryan3.jpg",
      "/images/bestSellings/Ryan4.jpg",
    ],
  },
  {
    id: 9,
    name: "Mafi Takahashi",
    price: 999,
    originalPrice: 999,
    inStock: true,
    onSale: false,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Mafi1.jpg",
      "/images/bestSellings/Mafi2.jpg",
      "/images/bestSellings/Mafi3.jpg",
      "/images/bestSellings/Mafi4.jpg",
    ],
  },
  {
    id: 10,
    name: "Mirei Matsumoto",
    price: 999,
    originalPrice: 1299,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Mirei1.jpg",
      "/images/bestSellings/Mirei2.jpg",
      "/images/bestSellings/Mirei3.jpg",
      "/images/bestSellings/Mirei4.jpg",
    ],
  },
  {
    id: 15,
    name: "Harumi Yoshida",
    price: 1199,
    originalPrice: 1499,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Harumi1.jpg",
      "/images/bestSellings/Harumi2.jpg",
      "/images/bestSellings/Harumi3.jpg",
      "/images/bestSellings/Harumi4.jpg",
    ],
  },
  {
    id: 17,
    name: "Hanuka Yamamoto",
    price: 799,
    originalPrice: 999,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Hanuka1.jpg",
      "/images/bestSellings/Hanuka2.jpg",
      "/images/bestSellings/Hanuka3.jpg",
      "/images/bestSellings/Hanuka4.jpg",
    ],
  },
  {
    id: 19,
    name: "Yuki Matsuda",
    price: 499,
    originalPrice: 699,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Yuki1.jpg",
      "/images/bestSellings/Yuki2.jpg",
      "/images/bestSellings/Yuki3.jpg",
      "/images/bestSellings/Yuki4.jpg",
    ],
  },
  {
    id: 21,
    name: "Sato",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Sato1.jpg",
      "/images/bestSellings/Sato2.jpg",
      "/images/bestSellings/Sato3.jpg",
      "/images/bestSellings/Sato4.jpg",
    ],
  },
  {
    id: 22,
    name: "Seyka",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Seyka1.jpg",
      "/images/bestSellings/Seyka2.jpg",
      "/images/bestSellings/Seyka3.jpg",
      "/images/bestSellings/Seyka4.jpg",
    ],
  },
  {
    id: 23,
    name: "Mako",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Mako1.jpg",
      "/images/bestSellings/Mako2.jpg",
      "/images/bestSellings/Mako3.jpg",
      "/images/bestSellings/Mako4.jpg",
    ],
  },
  {
    id: 37,
    name: "Xecty",
    price: 1999,
    originalPrice: 1999,
    inStock: true,
    onSale: false,
    category: "bestSellings",
    imageSrc: [
      "/images/bestSellings/Xecty1.jpg",
      "/images/bestSellings/Xecty2.jpg",
      "/images/bestSellings/Xecty3.jpg",
      "/images/bestSellings/Xecty4.jpg",
    ],
  },
];

export { newCollection, sale, bestSellings };
