const newCollection = [
  {
    id: 26,
    name: "Yuki",
    price: 1299,
    originalPrice: 1399,
    inStock: true,
    onSale: false,
    category: "newCollection",
    imageSrc: "/images/newCollection/Yuki.jpg",
  },
  {
    id: 25,
    name: "Hikari",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "newCollection",
    imageSrc: "/images/newCollection/hikari.jpg",
  },
  {
    id: 29,
    name: "Katsumi",
    price: 999,
    originalPrice: 1399,
    inStock: true,
    onSale: false,
    category: "newCollection",
    imageSrc: "/images/newCollection/Katsumi.jpg",
  },
  {
    id: 28,
    name: "Katsune",
    price: 1399,
    originalPrice: 1499,
    inStock: true,
    onSale: true,
    category: "newCollection",
    imageSrc: "/images/newCollection/Katsune.jpg",
  },
];

const sale = [
  {
    id: 5,
    name: "Asuka",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: "/images/sale/asuka.jpg",
  },
  {
    id: 6,
    name: "Usopp",
    price: 899,
    originalPrice: 1099,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: "/images/sale/usopp.jpg",
  },
  {
    id: 18,
    name: "Luffy",
    price: 999,
    originalPrice: 1299,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: "/images/sale/luffy.jpg",
  },

  {
    id: 11,
    name: "Leo",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: "/images/sale/leopard.jpg",
  },
];

const bestSellings = [
  {
    id: 19,
    name: "Yuki",
    price: 499,
    originalPrice: 699,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: "/images/bestSellings/teacher.jpg",
  },
  {
    id: 20,
    name: "LLenn",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "sale",
    imageSrc: "/images/sale/llen.jpg",
  },
  {
    id: 17,
    name: "Hanuka",
    price: 799,
    originalPrice: 999,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: "/images/bestSellings/hanuka.jpg",
  },
  {
    id: 23,
    name: "Mako",
    price: 1099,
    originalPrice: 1399,
    inStock: true,
    onSale: true,
    category: "bestSellings",
    imageSrc: "/images/bestSellings/Mako.jpg",
  },
];

export { newCollection, sale, bestSellings };
